# Generated by Django 3.2.18 on 2023-06-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userProfilPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('profilPicture', models.ImageField(blank=True, null=True, upload_to='user_picture/')),
            ],
        ),
    ]
