# Generated by Django 3.2.18 on 2023-06-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erttiwtBack', '0002_alter_userprofilpictures_profilpicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilpictures',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprofilpictures',
            name='user',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
