# Generated by Django 3.2.18 on 2023-06-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erttiwtBack', '0003_auto_20230605_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='userCoverPictures',
            fields=[
                ('user', models.IntegerField(primary_key=True, serialize=False)),
                ('coverPicture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
