# Generated by Django 2.2.28 on 2023-05-23 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twitt',
            fields=[
                ('idTwitt', models.AutoField(primary_key=True, serialize=False)),
                ('twitt', models.CharField(max_length=280)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=50)),
                ('likes', models.IntegerField(default=0)),
                ('retwitts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('idCommentaire', models.AutoField(primary_key=True, serialize=False)),
                ('commentaire', models.CharField(max_length=280)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=50)),
                ('twitt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erttiwtFront.Twitt')),
            ],
        ),
    ]
