# Generated by Django 2.2.28 on 2023-06-07 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erttiwtFront', '0001_initial'),
    ]

    operations = [
       
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('idMessage', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=1280)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.IntegerField()),
                ('destinataire', models.IntegerField()),
            ],
        ),
    ]
