# Generated by Django 3.2.18 on 2023-06-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erttiwtFront', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnements',
            fields=[
                ('idAbonnements', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('abonnement', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='twitt',
            name='twitt',
            field=models.TextField(help_text='280 caractères maximum', max_length=280, verbose_name='Quoi de neuf ?'),
        ),
    ]
