# Generated by Django 3.2.18 on 2023-06-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erttiwtFront', '0004_tweetretweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnements',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='user',
            field=models.IntegerField(),
        ),
    ]
