# Generated by Django 3.2.18 on 2023-06-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erttiwtFront', '0003_auto_20230607_0941'),
        ('erttiwtFront', '0005_auto_20230605_1951'),
    ]

    operations = [
    ]
