# Generated by Django 3.2.18 on 2023-06-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erttiwtFront', '0007_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='lu',
            field=models.BooleanField(default=False),
        ),
    ]
